; PyWebServer Config

[setting]
ServerPath=/www/wwwroot/pywebserver/Website
InstallPath=/www/wwwroot/pywebserver/Server
ip=("0.0.0.0")
port=99
ssl=false
ssljump-domain=netdisk.himpqblog.cn

[config]
threadpool-maxsize=1000
language-wrong-error=false
ranges-download=true
default-page=('index.html','index.htm','index.py')
python=true
raise-error=true
timeout=60
keep-alive-max=20
cachesize=409600
sameip-request-count=3
clean-threadtime=1055
server_status=NORMAL
errorpage-path=./ErrorPages/error.html
ssl-path=('./crts/server.crt','./crts/server.key','./crts/ca.crt')
ssl-password=
ssl-dohandshake=true
use-multiprocessing=false
enable-etag=false
maxsize-for-etag=(1024*1024*100)
enable-plugin=true
support-protocols=(["spdy/3.1", "h2", "http/1.1"])
collection-expire-time=3600

[black_list]
blacklist=

[bind_domains]
domains=

[http_errorcodes]
503=('Server Unavailable','Server overload or maintenance in progress. Please wait for administrator to maintain or visit later.')
404=('Not Found','Page is not found.')
406=('Language Error','The language is not supported by the server.')
safeguard=('Server Safeuard','The server is being maintained.')

[headers]
#.(flv|gif|jpg|jpeg|png|ico|swf)$=('Cache-control', 'max-age=2592000')

[HTTP2]
SETTINGS_HEADER_TABLE_SIZE=4096
SETTINGS_MAX_CONCURRENT_STREAMS=100
SETTINGS_INITAL_WINDOW_SIZE=65535
SETTINGS_MAX_FRAME_SIZE=16384
SETTINGS_MAX_HEADER_LIST_SIZE=16384

[logger]
ignore_list=([])